# Generated by Django 5.2 on 2025-04-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tier',
            field=models.CharField(choices=[('BASE', 'Base'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='BASE', max_length=10),
        ),
    ]
