# Generated by Django 5.2 on 2025-04-17 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inventory', 'Inventory'), ('order_summary', 'Order Summary'), ('stockouts', 'Stockouts'), ('Financial', 'Financial'), ('custom', 'Custom')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('visible_to_client', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='businesses.business')),
            ],
        ),
    ]
