# Generated by Django 5.2 on 2025-04-17 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('stockout', 'Stockout'), ('replacement', 'Replacement')], default='new', max_length=30)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('receiving_company', models.CharField(max_length=255)),
                ('receiving_address', models.TextField()),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('taxable', models.BooleanField(default=False)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.unit')),
            ],
        ),
    ]
